name: Check redwood kernel

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout redwood kernel
        uses: actions/checkout@v4
        with:
          repository: obaidaisj-cyber/Xiaomi_Kernel_OpenSource
          ref: redwood-oss
          fetch-depth: 1
          submodules: recursive

      - name: Verify kernel files
        run: |
          echo "Checking kernel files..."
          
          echo "Current directory:"
          pwd

          echo "Files:"
          ls -la

          echo "Checking required folders..."

          test -d drivers
          test -d arch
          test -f Makefile

          echo "Kernel source OK"
